"""initial schema

Revision ID: 480f96f6f857
Revises: 
Create Date: 2026-07-28 21:27:49.226955
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '480f96f6f857'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('keycloak_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_keycloak_sub'), 'users', ['keycloak_sub'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_log_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gitlab_group_id', sa.Integer(), nullable=True),
    sa.Column('gitlab_group_path', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_projects_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('integrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('ELASTIC', 'SENTRY', 'APPDYNAMICS', 'KEYCLOAK', name='integrationkind', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=True),
    sa.Column('base_url', sa.String(length=1024), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('secret_ref', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('UNVERIFIED', 'OK', 'FAILED', name='integrationstatus', native_enum=False), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_integrations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integrations')),
    sa.UniqueConstraint('project_id', 'kind', name='integrations_project_kind')
    )
    op.create_index(op.f('ix_integrations_project_id'), 'integrations', ['project_id'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=False),
    sa.Column('time_window_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'DONE', 'FAILED', 'CANCELLED', name='investigationstatus', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_investigations_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_investigations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigations'))
    )
    op.create_index('ix_investigations_project_created', 'investigations', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_investigations_project_id'), 'investigations', ['project_id'], unique=False)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_table('project_repos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('gitlab_project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.Enum('FE', 'BE', 'OTHER', name='repokind', native_enum=False), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('web_url', sa.String(length=1024), nullable=True),
    sa.Column('org_package_prefixes', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_repos_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_repos'))
    )
    op.create_index(op.f('ix_project_repos_project_id'), 'project_repos', ['project_id'], unique=False)
    op.create_table('investigation_result',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.Enum('BLOCKER', 'HIGH', 'MEDIUM', 'LOW', name='severity', native_enum=False), nullable=False),
    sa.Column('severity_rationale', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('root_cause_evidence', sa.JSON(), nullable=True),
    sa.Column('code_locations', sa.JSON(), nullable=True),
    sa.Column('suggested_fixes', sa.JSON(), nullable=True),
    sa.Column('third_party_involved', sa.Boolean(), nullable=False),
    sa.Column('third_party_details', sa.JSON(), nullable=True),
    sa.Column('occurrence_series', sa.JSON(), nullable=True),
    sa.Column('raw_model_output', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_result_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_result'))
    )
    op.create_index(op.f('ix_investigation_result_investigation_id'), 'investigation_result', ['investigation_id'], unique=True)
    op.create_table('investigation_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investigation_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('running', 'ok', 'failed', 'skipped', name='stepstatus', native_enum=False), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], name=op.f('fk_investigation_steps_investigation_id_investigations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_investigation_steps')),
    sa.UniqueConstraint('investigation_id', 'seq', name='investigation_steps_inv_seq')
    )
    op.create_index(op.f('ix_investigation_steps_investigation_id'), 'investigation_steps', ['investigation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_steps_investigation_id'), table_name='investigation_steps')
    op.drop_table('investigation_steps')
    op.drop_index(op.f('ix_investigation_result_investigation_id'), table_name='investigation_result')
    op.drop_table('investigation_result')
    op.drop_index(op.f('ix_project_repos_project_id'), table_name='project_repos')
    op.drop_table('project_repos')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_project_id'), table_name='investigations')
    op.drop_index('ix_investigations_project_created', table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_integrations_project_id'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_keycloak_sub'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
